name: Download Audi PDF (Direct Link)

on:
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run downloader script
        run: python download_pdf.py

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: audi-offer
          path: audi-offer.pdf
